id: P5022C2DA
initial_creation_type: input
source_metadata:
  title: Mālinīślokavārttika
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Śaiva
  data entry: Jürgen Hanneder
  contribution to GRETIL: Jürgen Hanneder
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:05:23.161273'
last_modified_at: '2022-03-09T15:05:23.161290'
